Move global private variables to standard namespace

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1441,9 +1441,9 @@ job:kill () {
 coproc:run () {
 	[[ $# -gt 1 && $1 ]] || errorf || return
 
-	declare -g -A __coproc
+	declare -g -A _x__coproc
 
-	[[ ${__coproc[$1]} -gt 0 ]] && return
+	[[ ${_x__coproc[$1]} -gt 0 ]] && return
 
 	valid_name "$1" || errorf "Invalid coprocess name" || return
 
@@ -1455,9 +1455,9 @@ coproc:run () {
 
 	coproc "$@"
 
-	__coproc[$name]=$COPROC_PID
-	__coproc[$name:0]=${COPROC[0]}
-	__coproc[$name:1]=${COPROC[1]}
+	_x__coproc[$name]=$COPROC_PID
+	_x__coproc[$name:0]=${COPROC[0]}
+	_x__coproc[$name:1]=${COPROC[1]}
 
 	_trace && trace "Running coprocess $COPROC_PID $name: $*"
 
@@ -1467,15 +1467,15 @@ coproc:run () {
 coproc:kill () {
 	[[ $# -eq 1 && $1 ]] || errorf || return
 
-	local pid=${__coproc[$1]}
+	local pid=${_x__coproc[$1]}
 
 	[[ $pid ]] || errorf "Unknown coprocess" || return
 
 	[[ $pid -eq 0 ]] && return
 
-	unset -v __coproc[$1:0] __coproc[$1:1]
+	unset -v _x__coproc[$1:0] _x__coproc[$1:1]
 
-	__coproc[$1]=0
+	_x__coproc[$1]=0
 
 	job:kill $pid
 }
@@ -1483,7 +1483,7 @@ coproc:kill () {
 coproc:write () {
 	[[ $# -gt 1 ]] || errorf || return
 
-	local fd=${__coproc[$1:1]}; shift
+	local fd=${_x__coproc[$1:1]}; shift
 
 	[[ $fd ]] || errorf "Unknown coprocess" || return
 
@@ -1501,7 +1501,7 @@ coproc:write () {
 coproc:read_line () {
 	[[ $# -eq 1 ]] || errorf || return
 
-	local fd=${__coproc[$1:0]}; shift
+	local fd=${_x__coproc[$1:0]}; shift
 
 	[[ $fd ]] || errorf "Unknown coprocess" || return
 
@@ -1511,7 +1511,7 @@ coproc:read_line () {
 coproc:read_field () {
 	[[ $# -eq 1 ]] || errorf || return
 
-	local fd=${__coproc[$1:0]}; shift
+	local fd=${_x__coproc[$1:0]}; shift
 
 	[[ $fd ]] || errorf "Unknown coprocess" || return
 
@@ -1790,11 +1790,11 @@ output: () {
 defer () {
 	[[ $# -ge 1 ]] || errorf || return
 
-	declare -g -a __defer_p __defer_s __defer_c
+	declare -g -a _x__defer_p _x__defer_s _x__defer_c
 
-	__defer_p+=($BASHPID)
-	__defer_s+=(${#@})
-	__defer_c+=("$@")
+	_x__defer_p+=($BASHPID)
+	_x__defer_s+=(${#@})
+	_x__defer_c+=("$@")
 
 	trap __defer_ EXIT
 }
@@ -1804,19 +1804,19 @@ __defer_ () {
 	_trace && trace "Defer begin: main"
 
 	local err len
-	while [[ ${#__defer_s[@]} -gt 0 ]]; do
-		[[ ${__defer_p[-1]} == $BASHPID ]] || break
+	while [[ ${#_x__defer_s[@]} -gt 0 ]]; do
+		[[ ${_x__defer_p[-1]} == $BASHPID ]] || break
 
-		_trace && trace "Running defer #${#__defer_s[@]}"
+		_trace && trace "Running defer #${#_x__defer_s[@]}"
 
-		err= len=${__defer_s[-1]}
+		err= len=${_x__defer_s[-1]}
 
-		run "${__defer_c[@]: -len}" || err=$?
+		run "${_x__defer_c[@]: -len}" || err=$?
 
-		[[ $err ]] && _trace && trace "Error defer #${#__defer_s[@]}: $err"
+		[[ $err ]] && _trace && trace "Error defer #${#_x__defer_s[@]}: $err"
 
-		__defer_c=("${__defer_c[@]:0:${#__defer_c[@]}-len}")
-		unset -v __defer_s'[-1]' __defer_p'[-1]'
+		_x__defer_c=("${_x__defer_c[@]:0:${#_x__defer_c[@]}-len}")
+		unset -v _x__defer_s'[-1]' _x__defer_p'[-1]'
 	done
 
 	_trace && trace "Defer end: main"
