Add ephemeral port generator function

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -512,6 +512,26 @@ valid_bool () {
 	bool "$1" || [[ $? -ne 3 ]]
 }
 
+require_command () {
+	[[ $# -eq 1 ]] || errorf || return
+
+	is_command "$1" || error "Command required: $1"
+}
+
+port_opened () {
+    [[ $# -ge 1 && $# -le 3 ]] || errorf || return
+
+    local port=$1 addr=${2:-127.0.0.1} proto=${3:-tcp}
+
+    valid_uint "$port" || errorf "Invalid port: $port" || return
+
+    [[ $addr =~ ^[[:digit:]]+(\.[[:digit:]]+){3}$ ]] || errorf "Invalid address: $addr" || return
+
+    [[ $proto == tcp || $proto == udp ]] || errorf "Invalid protocol: $proto" || return
+
+    { : > /dev/$proto/$addr/$port; } &>/dev/null || return 1
+}
+
 contains () {
 	[[ $# -ge 1 ]] || errorf || return
 
@@ -1247,10 +1267,24 @@ tmp_dir () {
 	TMP_DIR=$tmp
 }
 
-require_command () {
-	[[ $# -eq 1 ]] || errorf || return
+ephemeral_port () {
+    [[ $# -eq 0 ]] || errorf || return
 
-	is_command "$1" || error "Command required: $1"
+    require_command nc
+
+    local port
+
+    coproc:run __ephemeral_port__ 'nc -lv 127.0.0.1 0 2>&1' || return
+
+    if coproc:read_line __ephemeral_port__; then
+		port=${COPROC_DATA##*[![:digit:]]}
+    fi
+
+	coproc:kill __ephemeral_port__ || :
+
+	[[ $port && $port != *[![:digit:]]* ]] || return
+
+    EPHEMERAL_PORT=$port
 }
 
 run () {
@@ -1323,7 +1357,7 @@ coproc:run () {
 
 	declare -g -A __coproc
 
-	[[ ${__coproc[$1]} ]] && return
+	[[ ${__coproc[$1]} -gt 0 ]] && return
 
 	valid_name "$1" || errorf "Invalid coprocess name" || return
 
@@ -1351,7 +1385,11 @@ coproc:kill () {
 
 	[[ $pid ]] || errorf "Unknown coprocess" || return
 
-	unset -v __coproc'['$1{,:{0,1}}']'
+	[[ $pid -eq 0 ]] && return
+
+	unset -v __coproc[$1:0] __coproc[$1:1]
+
+	__coproc[$1]=0
 
 	job:kill $pid
 }
@@ -1826,6 +1864,8 @@ _var () {
 # member set
 
 =# () {
+	{}=# "$@" && return || [[ $? -eq 3 ]] || return 2
+
 	errorf
 }
 
@@ -1939,6 +1979,16 @@ _var () {
 	[[ $# -ge 2 ]] || errorf || return
 
 	__v "$1" "$2" || return
+
+	local _x_v=$1 _x_a; __s $1 _x_a || return
+
+	errorf
+}
+
+{}=# () {
+	[[ $# -ge 2 ]] || errorf || return
+
+	__v "$1" "$3" && __f "$2" || return
 
 	local _x_v=$1 _x_a; __s $1 _x_a || return
 
